spring:
  config:
    import:
      - classpath:/secret/application-secret.yml

jwt:
  expiration-time-ms: 8640000000 # 24 hours * 100
  cookie:
    secure: false # development에서는 false, production에서는 true

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    database: mysql
    defer-datasource-initialization: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/gyohwan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gyohwan_dev_username
    password: gyohwan_dev_password

jwt:
  secret-key: OWI3OWUzZGMtMTllYy00NmE2LWJlMDctMDZkZTlkYzMzYzg2