spring:
  config:
    import: "optional:classpath:secret/application-secret.yml"

jwt:
  expiration-time-ms: 86400000 # 24 hours

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    database: mysql
    defer-datasource-initialization: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/gyohwan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gyohwan_dev_username
    password: gyohwan_dev_password

jwt:
  secret-key:
    OWI3OWUzZGMtMTllYy00NmE2LWJlMDctMDZkZTlkYzMzYzg2
