name: CI/CD - Build and Push Docker Image & Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .       # Dockerfile이 있는 경로
          push: true       # 푸시 실행
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gyohwan-compass:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gyohwan-compass:latest
            sudo docker stop gyohwan-compass-container || true
            sudo docker rm gyohwan-compass-container || true
            sudo docker run -d -p 8080:8080 --name gyohwan-compass-container ${{ secrets.DOCKERHUB_USERNAME }}/gyohwan-compass:latest
